repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.10
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: ty-check
        name: ty-check
        language: python
        entry: ./.venv/bin/ty check
        pass_filenames: false
        additional_dependencies: [ty]
        always_run: true
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: ./.venv/bin/pytest tests
        language: python
        pass_filenames: false
        always_run: true
